### ISSUE TITLE
Space bar crashes `redo` on first use

### ISSUE THREAD

**Issue by brandondrew** [barthr/redo#10]
I just installed `redo` and ran it, to a blank list of commands in the history.  Okay, no problem.  But when I hit <kbd>space</kbd>, it crashed:

```
Caught panic:

interface conversion: list.Item is nil, not *ui.HistoryItem

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack(0x63, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/debug/stack.go:24 +0x88
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/debug/stack.go:16 +0x20
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3(0x140000bc280)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.19.3/tea.go:350 +0xb4
panic(0x100688360, 0x14000192c90)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/panic.go:971 +0x3f4
github.com/barthr/redo/ui.HistoryItemListComponent.Update(0x10101000101, 0x10062569d, 0x29, 0x14000090ea0, 0x0, 0x0, 0x14000090e40, 0x0, 0x0, 0x14000090f00, ...)
	/home/runner/work/redo/redo/ui/history_list_component.go:64 +0x658
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0x140000bc280, 0x0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.19.3/tea.go:534 +0x670
github.com/charmbracelet/bubbletea.(*Program).Start(...)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.19.3/tea.go:543
main.runTeaProgram(0x1006c3738, 0x140000f7200)
	/home/runner/work/redo/redo/main.go:91 +0x44
main.main()
	/home/runner/work/redo/redo/main.go:79 +0x2e4
```

**Comment by barthr** [comment]
Hi, thanks for reporting. I will have a look into fixing this!
